spring.application.name=SpringBoot_REST
server.port=8080

global_weather_baseurl=http://localhost:8081
app.base-url=http://localhost:8080


spring.datasource.url=jdbc:mysql://localhost:3306/Weather_Rest
spring.datasource.username=root
spring.datasource.password=Subhendu@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# actuator
management.endpoints.web.exposure.include=*


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subhendujena2002@gmail.com
spring.mail.password=xhzk cfzy zqpr ajnh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# request body validation
spring.jackson.deserialization.fail-on-unknown-properties=true
